name: pubmed-connections
dependencies:
  - numpy
  - scikit-learn
  - lxml
  - neo4j-python-driver=4.4.0
  - pip
  - pip:
    - flask==2.1.2
    - types-Flask
    - atomics
    - flask-restx
    - graphdatascience
    - flask-jwt-extended
    - flask-cors
    - werkzeug<=2.1.2
